<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#01-Jupyter-Usual-Keyboard-Shortcuts" data-toc-modified-id="01-Jupyter-Usual-Keyboard-Shortcuts-1">01 Jupyter Usual Keyboard Shortcuts</a></span></li><li><span><a href="#02-Jupyter-Magic-Command" data-toc-modified-id="02-Jupyter-Magic-Command-2">02 Jupyter Magic Command</a></span><ul class="toc-item"><li><span><a href="#%run" data-toc-modified-id="%run-2.1">%run</a></span></li><li><span><a href="#%timeit" data-toc-modified-id="%timeit-2.2">%timeit</a></span></li></ul></li><li><span><a href="#03-Numpy-Basic-Kownlage" data-toc-modified-id="03-Numpy-Basic-Kownlage-3">03 Numpy Basic Kownlage</a></span><ul class="toc-item"><li><span><a href="#3.1-常用函数" data-toc-modified-id="3.1-常用函数-3.1">3.1 常用函数</a></span><ul class="toc-item"><li><span><a href="#numpy.arange" data-toc-modified-id="numpy.arange-3.1.1">numpy.arange</a></span></li><li><span><a href="#numpy.linspace" data-toc-modified-id="numpy.linspace-3.1.2">numpy.linspace</a></span></li><li><span><a href="#numpy.random" data-toc-modified-id="numpy.random-3.1.3">numpy.random</a></span></li><li><span><a href="#numpy.reshape" data-toc-modified-id="numpy.reshape-3.1.4">numpy.reshape</a></span></li></ul></li><li><span><a href="#3.2-numpy.array基础" data-toc-modified-id="3.2-numpy.array基础-3.2">3.2 numpy.array基础</a></span></li><li><span><a href="#3.3-numpy.array的多种创建方式" data-toc-modified-id="3.3-numpy.array的多种创建方式-3.3">3.3 numpy.array的多种创建方式</a></span></li><li><span><a href="#3.4-numpy.array基本属性" data-toc-modified-id="3.4-numpy.array基本属性-3.4">3.4 numpy.array基本属性</a></span><ul class="toc-item"><li><span><a href="#数据准备-数组x矩阵X" data-toc-modified-id="数据准备-数组x矩阵X-3.4.1">数据准备-数组x矩阵X</a></span></li><li><span><a href="#查看数组维度" data-toc-modified-id="查看数组维度-3.4.2">查看数组维度</a></span></li><li><span><a href="#查看数组形状" data-toc-modified-id="查看数组形状-3.4.3">查看数组形状</a></span></li><li><span><a href="#查看元素个数" data-toc-modified-id="查看元素个数-3.4.4">查看元素个数</a></span></li></ul></li><li><span><a href="#3.5-numpy.array的数据取出" data-toc-modified-id="3.5-numpy.array的数据取出-3.5">3.5 numpy.array的数据取出</a></span><ul class="toc-item"><li><span><a href="#一维数组的切片" data-toc-modified-id="一维数组的切片-3.5.1">一维数组的切片</a></span></li><li><span><a href="#二维数组的切片" data-toc-modified-id="二维数组的切片-3.5.2">二维数组的切片</a></span></li></ul></li><li><span><a href="#3.6-numpy.array的数据合并" data-toc-modified-id="3.6-numpy.array的数据合并-3.6">3.6 numpy.array的数据合并</a></span><ul class="toc-item"><li><span><a href="#行合并" data-toc-modified-id="行合并-3.6.1">行合并</a></span></li><li><span><a href="#列合并" data-toc-modified-id="列合并-3.6.2">列合并</a></span></li><li><span><a href="#不同维度数组合并" data-toc-modified-id="不同维度数组合并-3.6.3">不同维度数组合并</a></span></li><li><span><a href="#数据堆叠" data-toc-modified-id="数据堆叠-3.6.4">数据堆叠</a></span></li></ul></li><li><span><a href="#3.7-numpy.array的数据分割" data-toc-modified-id="3.7-numpy.array的数据分割-3.7">3.7 numpy.array的数据分割</a></span><ul class="toc-item"><li><span><a href="#一维数组分割" data-toc-modified-id="一维数组分割-3.7.1">一维数组分割</a></span></li><li><span><a href="#二维数组分割" data-toc-modified-id="二维数组分割-3.7.2">二维数组分割</a></span></li></ul></li><li><span><a href="#3.8-numpy.array的运算" data-toc-modified-id="3.8-numpy.array的运算-3.8">3.8 numpy.array的运算</a></span><ul class="toc-item"><li><span><a href="#常规运算" data-toc-modified-id="常规运算-3.8.1">常规运算</a></span></li><li><span><a href="#矩阵运算" data-toc-modified-id="矩阵运算-3.8.2">矩阵运算</a></span></li><li><span><a href="#聚合运算" data-toc-modified-id="聚合运算-3.8.3">聚合运算</a></span></li></ul></li><li><span><a href="#3.9-numpy.array索引和排序" data-toc-modified-id="3.9-numpy.array索引和排序-3.9">3.9 numpy.array索引和排序</a></span><ul class="toc-item"><li><span><a href="#一维数组" data-toc-modified-id="一维数组-3.9.1">一维数组</a></span></li><li><span><a href="#二维数组" data-toc-modified-id="二维数组-3.9.2">二维数组</a></span></li></ul></li><li><span><a href="#3.10-Fancy-Indexing" data-toc-modified-id="3.10-Fancy-Indexing-3.10">3.10 Fancy Indexing</a></span></li><li><span><a href="#3.11-numpy.array的比较" data-toc-modified-id="3.11-numpy.array的比较-3.11">3.11 numpy.array的比较</a></span></li></ul></li></ul></div>

# 01 Jupyter Usual Keyboard Shortcuts
Shift-Enter: 运行代码块, 选择下面的代码块

Ctrl-Enter: 运行选中的代码块

Alt-Enter: 运行代码块并且插入下面

# 02 Jupyter Magic Command

## %run

In [40]:
# 加载脚本文件
%run D:/PycharmProjects/hello.py

In [41]:
say_hello_to('hjy')

hello,hjy


## %timeit

In [42]:
# 测试一行命令的执行效率
%time L = [i**2 for i in range(1000)]

Wall time: 0 ns


In [43]:
# 多次测试一行命令的执行效率，选择最好的一次结果
%timeit L = [i**2 for i in range(1000)]

278 µs ± 2.31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [44]:
%%timeit
# 测试整个Cell的执行效率
# %%timeit必须写在Cell的第一行
L = []
for i in range(1000):
    L.append(i**2)

316 µs ± 3.02 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


# 03 Numpy Basic Kownlage

In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.4'

## 3.1 常用函数

### numpy.arange

In [47]:
# python中range步长只能是整型,默认为1
arr_python = [i for i in range(1,10,2)]
arr_python

[1, 3, 5, 7, 9]

In [48]:
# numpy中arange步长可以是浮点数
arr_numpy = np.arange(0,1,0.2)
arr_numpy

array([0. , 0.2, 0.4, 0.6, 0.8])

### numpy.linspace

In [49]:
#从1到20中等长截取5个端点，包含20
arr_space = np.linspace(0,20,5)
arr_space

array([ 0.,  5., 10., 15., 20.])

### numpy.random

In [50]:
# 生成[1,10)之间的一个随机整数
num = np.random.randint(1,10)
num

5

In [51]:
# 生成含有5个元素的向量，每个元素都是[1,10)之间的一个随机整数
rand_vec = np.random.randint(1,10,5)
rand_vec

array([9, 2, 5, 5, 7])

In [34]:
# 生成一个三行五列的随机矩阵
rand_matrix = np.random.randint(1,10,size=(3,5))
rand_matrix

array([[2, 4, 3, 4, 4],
       [7, 9, 1, 8, 5],
       [8, 2, 1, 8, 6]])

In [35]:
# 生成一个符合正态分布的随机数列Normal(m,n,size)，均值为m,标准差为n,共计size个元素
np.random.normal(0,1,10)

array([-0.61692337, -0.5772749 , -0.60604484, -0.8521119 , -0.46257818,
        2.06146537,  0.3014219 ,  0.80532105, -1.00695244, -0.450687  ])

### numpy.reshape

In [12]:
# 将一维数组变成二维矩阵
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
A = x.reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
# 转化成矩阵时，只指定行或列的元素个数，相应的列或行传入参数为-1，由numpy自动计算得出
# 指定矩阵B为5行，列数根据x元素个数决定，B的行数*列数 = x的元素个数
B = x.reshape(5,-1)
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

## 3.2 numpy.array基础

python中的List 每个元素可以为不同类型，非常灵活，但运算效率低

python中的Array 每个元素为同一类型，不够灵活，但效率高

In [ ]:
import array

In [ ]:
# 创建一个数组arr，其中每个元素均为整型，由参数i指定类型
arr  = array.array('i', [i for i in range(5)])
arr

numpy中的Array 每个元素为同一类型,以向量的形式保存数组，适用于向量运算，效率高

In [ ]:
nparr = np.array([i for i in range(10)])
nparr

In [ ]:
nparr[5] = 100
nparr

In [ ]:
# 返回当前nparr存储数据的类型
nparr.dtype

In [ ]:
# 将浮点数赋值给类型为Int的Array时,浮点数会自动转化为Int
nparr[5] = 3.14
nparr

In [ ]:
# Array的类型是初始化的时候确定的
nparr2 = np.array([1,2,3.14])
nparr2.dtype

In [ ]:
nparr2

## 3.3 numpy.array的多种创建方式

In [ ]:
# 创建包含十个元素的零向量，默认为浮点型
nparr3 = np.zeros(10)
nparr3

In [ ]:
nparr3.dtype

In [ ]:
# 创建包含十个整型元素的零向量
nparr4 = np.zeros(10, dtype=int)
nparr4

In [ ]:
# 创建三行五列的零矩阵
nparr5 = np.zeros((3,5))
nparr5

In [ ]:
# 创建三行五列，整型元素的零矩阵
nparr6 = np.zeros(shape=(3,5), dtype=int)
nparr6

In [ ]:
# 获得全1的矩阵
one = np.ones(shape=(3,5))
one

In [ ]:
# 获得值全为x的矩阵,x_arr的数据类型与x相同
x = 5
x_arr = np.full(shape=(3,5), fill_value=x)
x_arr

## 3.4 numpy.array基本属性

### 数据准备-数组x矩阵X

In [ ]:
x = np.arange(10)
x

In [ ]:
# 由包含15个元素的一维向量，转化成一个三行五列的矩阵
X = np.arange(15).reshape(3,5)
X

### 查看数组维度

In [ ]:
x.ndim

In [ ]:
X.ndim

### 查看数组形状

In [ ]:
x.shape
# 返回一个tuple，(第一维元素个数，第二维元素个数)

In [ ]:
X.shape

### 查看元素个数

In [ ]:
# 当前矩阵包含的元素个数
X.size

## 3.5 numpy.array的数据取出

### 一维数组的切片

In [ ]:
# 倒数第2个元素
x[-2]

In [ ]:
# 取第一到第四个元素
x[1:5]

In [ ]:
# 以2为步长 取第一到第八个元素之间的数据
x[0:9:2]

In [ ]:
# 当步长为-1时，表示先将数组倒序排列，然后取出相应片段
x[5::-1]

### 二维数组的切片

In [ ]:
# 取矩阵X的前两行*前三列
X[:2,:3]

In [ ]:
# 特别注意X[:2][:3]无法实现上述效果，
# 其解析过程：
# 首先解析X[:2]，解析结果记作Y
    # 取出X的前两个元素[ 0,  1,  2,  3,  4], [ 5,  6,  7,  8,  9]
    # Y = [[ 0,  1,  2,  3,  4], [ 5,  6,  7,  8,  9]]
# 然后解析Y[:3]
    # 取出Y的前三个元素
    # 由于Y只有两个元素，故而取出结果还是Y
X[:2][:3]

In [ ]:
# 取出前两行，对于所有列步长为2进行取出
X[:2, ::2]

In [ ]:
# 分别对行列进行倒序
X[::-1, ::-1]

In [ ]:
# 矩阵降维，只取第一行
# X[0] 或 X[0,:]
X[0, :]

In [ ]:
# 矩阵降维，只取第一列
X[:, 0]

In [ ]:
# numpy中，子矩阵改变，原矩阵也跟着改变
# 相应的改变原矩阵X的值后，子矩阵也跟着改变
# 但python中，使用List则没有这个问题
subX = X[:2, :3]
subX

In [ ]:
# 改变子矩阵subX的一行二列
subX[0,1] = 100
subX

In [ ]:
# 此时原矩阵X的一行二列的数据也改变了
X

In [ ]:
# 生成一个和原矩阵无关联的子矩阵，此时双方的改变不影响对方
subY = X[:2, :3].copy()
subY

In [ ]:
subY[0, 1] = 66
subY

In [ ]:
# 此时原矩阵X还是保持不变
X

## 3.6 numpy.array的数据合并

### 行合并

沿行方向等价于对列操作

沿列方向是对行进行操作

In [ ]:
# 多个二维矩阵的行合并 两个2*3合并变成一个4*3
M = np.array([[111,111,111],
            [222,222,222]])
N = np.array([[333,333,333],
            [222,222,222]])
MN = np.concatenate([M,N])
MN

### 列合并

In [60]:
# 将多个一维array传入一个List，然后合并成一行多列
a = np.array([111,111,111])
b = np.array([222,222,222])
c = np.array([333,333,333])
abc_list = [a,b,c]
abc_list

[array([111, 111, 111]), array([222, 222, 222]), array([333, 333, 333])]

In [61]:
abc = np.concatenate(abc_list)
abc

array([111, 111, 111, 222, 222, 222, 333, 333, 333])

In [56]:
# 多个二维矩阵列合并 两个2*3合并变成一个2*6
M = np.array([[111,111,111],
            [222,222,222]])
N = np.array([[333,333,333],
            [222,222,222]])
# axis默认为0，代表第一维度，行列中的行，为1时代表第二维度，列。为n-1时，代表第n维度，用于高纬矩阵
MN = np.concatenate([M,N],axis=1)
MN

array([[111, 111, 111, 333, 333, 333],
       [222, 222, 222, 222, 222, 222]])

In [57]:
# 另一种合并方法，水平方向堆叠
MN_horizontal = np.hstack([M,N])
MN_horizontal

array([[111, 111, 111, 333, 333, 333],
       [222, 222, 222, 222, 222, 222]])

### 不同维度数组合并

In [62]:
# 一维数组与二维矩阵的合并，需要先将一维数组reshape成2维的
c.reshape(1,-1)

array([[333, 333, 333]])

In [63]:
Mc = np.concatenate([M,c.reshape(1,-1)])
Mc

array([[111, 111, 111],
       [222, 222, 222],
       [333, 333, 333]])

In [65]:
# 另外一种更简便的方法
# 使用vstack,将传入List中的元素以垂直方向堆叠合并在一起，容错性更好
Mc_vertical = np.vstack([M,c])
Mc_vertical

array([[111, 111, 111],
       [222, 222, 222],
       [333, 333, 333]])

### 数据堆叠

In [69]:
# 将同一个一维数组垂直方向堆叠两次
# 将向量c摞两次
np.vstack([c] * 2)

array([[333, 333, 333],
       [333, 333, 333]])

In [72]:
# 另一种方法tile(x,(m,n))
# 将向量x在行维度上堆叠m次，列维度上堆叠n次
np.tile(c,(2,1))

array([[333, 333, 333],
       [333, 333, 333]])

In [73]:
np.tile(c,(2,2))

array([[333, 333, 333, 333, 333, 333],
       [333, 333, 333, 333, 333, 333]])

## 3.7 numpy.array的数据分割

### 一维数组分割

In [ ]:
x = np.random.randint(1,10,10)
x

In [ ]:
# 将x分割成三段，第一段是第一个到第三个，第二段是第四个到第七个，第三段是第八个到第十个
# split第一个参数传入要分割的数据，第二个参数传入分割点List
x1, x2, x3 = np.split(x,[3,7])

In [ ]:
x1

In [ ]:
x2

In [ ]:
x3

In [ ]:
# 将x平均分割成两段
x_left, x_right = np.split(x,[5])
x_left

In [ ]:
x_right

### 二维数组分割

In [ ]:
matrix = np.random.randint(1,10,(4,6))
matrix

In [ ]:
# 垂直方向（第一维度方向、行方向）上下分割
matrix1,matrix2 = np.split(matrix,[2])
matrix1

In [ ]:
matrix2

In [ ]:
# 另一种方法,垂直方向以2这个点上下分割
upper, lower = np.vsplit(matrix,[2])
upper

In [ ]:
lower

In [ ]:
# 水平方向（第二维度方向、列方向）左右分割
matrix3,matrix4 = np.split(matrix,[3,],axis=1)
matrix3

In [ ]:
matrix4

In [ ]:
# 另一种方法
left, right = np.hsplit(matrix,[3])
left

In [ ]:
right

## 3.8 numpy.array的运算

### 常规运算

In [81]:
D = np.arange(1, 16).reshape(3, 5)
D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
# 针对D中的每个元素dij，求e的dij次方，组成新的矩阵
eX = np.exp(D)
eX

In [ ]:
np.log(eX)

In [ ]:
np.log2(D)

In [ ]:
np.log10(D)

In [ ]:
# 针对D中的每一个元素dij，求3的dij次方
np.power(3, D)

### 矩阵运算

In [ ]:
P = np.full((2,2),10)
P

In [ ]:
Q = np.arange(1,5).reshape(2,2)
Q

In [ ]:
# 对应元素相乘,不符合矩阵乘法定义
P*Q

In [ ]:
# 真正的矩阵乘法
P.dot(Q)

In [ ]:
# 对应元素浮点相除
P/Q

In [ ]:
# 对应元素整除
P // Q

In [54]:
# 矩阵转置
Q.T

array([[1, 3],
       [2, 4]])

In [76]:
# 方阵的逆
invQ = np.linalg.inv(Q)
invQ

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [78]:
# 逆方阵的性质，原方阵*逆 = 单位矩阵E
E = Q.dot(invQ)
E

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [88]:
# 对于不是方阵的矩阵，可以求其伪矩阵
U = np.arange(16).reshape(2,8)
U

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [90]:
pinvU = np.linalg.pinv(U)
pinvU

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -1.04083409e-17],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [91]:
# 伪逆矩阵仍然满足逆矩阵性质，原矩阵*伪逆矩阵 近似 E
U.dot(pinvU)

array([[ 1.00000000e+00, -2.49800181e-16],
       [ 0.00000000e+00,  1.00000000e+00]])

In [1]:
# 向量矩阵相乘：
# numpy会自动进行矩阵的行列对其
# 比如2*1 与 2*2 相乘，自动转化为1*2 与 2*2相乘

### 聚合运算

In [4]:
# 一维数组聚合
ary = np.arange(15)
ary

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
# 求和
ary.sum()

105

In [6]:
np.sum(ary)

105

In [7]:
# 求最大值
ary.max()

14

In [8]:
np.max(ary)

14

In [15]:
# 求最小值
ary.min()

0

In [17]:
np.min(ary)

0

In [19]:
# 二维数组聚合
Ary = np.arange(16).reshape(4,-1)
Ary

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
# 求矩阵中所有元素的累加和
np.sum(Ary)

120

In [21]:
# 求矩阵每一列的累加和，沿行方向进行计算，axis=0，将行压缩掉
np.sum(Ary, axis=0)

array([24, 28, 32, 36])

In [23]:
# 求矩阵每一行的累加和，沿列方向进行计算，axis=1，将列压缩掉
np.sum(Ary,axis=1)

array([ 6, 22, 38, 54])

In [24]:
# 求矩阵所有元素的累成积
Ary+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [25]:
np.prod(Ary+1)

2004189184

In [26]:
# 求平均值
np.mean(Ary)

7.5

In [28]:
# 求中位数
np.median(Ary)

7.5

In [30]:
# 求百分位点
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(Ary,q = percent))

0.0
3.75
7.5
11.25
15.0


In [31]:
# 求方差
np.var(Ary)

21.25

In [33]:
# 标准差
np.std(Ary)

4.6097722286464435

## 3.9 numpy.array索引和排序

### 一维数组

In [41]:
# 获得最小值的索引
index = np.argmin(ary)
index

0

In [43]:
# 使用索引访问最小值
ary[index]

0

In [8]:
# 创建向量
vector = np.arange(15)
vector

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
# 对vector进行乱序操作
np.random.shuffle(vector)
vector

array([ 5,  8,  0,  4, 10, 13,  9, 12,  2,  7,  3, 14,  6, 11,  1])

In [10]:
# 对vector进行排序
new_vec = np.sort(vector)
new_vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
# 排序后原向量vector不发生改变
vector

array([ 5,  8,  0,  4, 10, 13,  9, 12,  2,  7,  3, 14,  6, 11,  1])

In [13]:
# 以数值3为中心点进行快排的一次划分
# 划分结果，小于3的都在3的左边，大于3的都在右边
np.partition(vector, 3)

array([ 1,  0,  2,  3,  4,  5,  9,  8, 13,  7, 10, 14,  6, 11, 12])

In [14]:
# 先对数组进行排序，然后按排序结果返回元素在原数组中的索引下标
np.argsort(vector)

array([ 2, 14,  8, 10,  3,  0, 12,  9,  1,  6,  4, 13,  7,  5, 11],
      dtype=int64)

### 二维数组

In [4]:
# 生成一个4*4的随机矩阵，元素均小于10
rand_arr = np.random.randint(10, size=(4,4))
rand_arr

array([[0, 3, 8, 2],
       [0, 4, 0, 4],
       [1, 1, 0, 3],
       [3, 8, 3, 0]])

In [5]:
# 二维数组排序,只进行行内排序
np.sort(rand_arr)

array([[0, 2, 3, 8],
       [0, 0, 4, 4],
       [0, 1, 1, 3],
       [0, 3, 3, 8]])

In [7]:
# 只对列进行排序，axis=0 沿行方向进行操作，排的是列的顺序
np.sort(rand_arr, axis=0)

array([[0, 1, 0, 0],
       [0, 3, 0, 2],
       [1, 4, 3, 3],
       [3, 8, 8, 4]])

In [15]:
# 返回排序后得原数组索引
np.argsort(rand_arr, axis=1)

array([[0, 3, 1, 2],
       [0, 2, 1, 3],
       [2, 0, 1, 3],
       [3, 0, 2, 1]], dtype=int64)

## 3.10 Fancy Indexing

In [26]:
L = np.random.randint(15,size=15)
L

array([ 2,  8, 14,  3,  4,  4, 13,  4,  8,  3, 11, 13,  0,  0,  9])

In [27]:
# 想要同时访问索引下标为3,5,8的元素
indexs = [3, 5, 8]
L[indexs]

array([3, 4, 8])

In [28]:
# 不仅访问3,5,7,8，同时还要以[3,5],[7,8]的结构返回结果
inds = np.array([[3, 5], 
                 [7, 8]])
L[inds]

array([[3, 4],
       [4, 8]])

In [29]:
S = L.reshape(5,-1)
S

array([[ 2,  8, 14],
       [ 3,  4,  4],
       [13,  4,  8],
       [ 3, 11, 13],
       [ 0,  0,  9]])

In [30]:
# 访问二维数组中的点(0,0) 点(1,1) 点(2,2)
# 设置行索引
row = [0,1,2]
# 设置列索引
col = [0,1,2]
S[row,col]

array([2, 4, 8])

In [31]:
# 访问前两行的第0,1,2列
S[:2,col]

array([[ 2,  8, 14],
       [ 3,  4,  4]])

## 3.11 numpy.array的比较

In [4]:
x = np.random.randint(15,size=10)
x

array([14,  8,  4,  4,  1,  6,  0,  2,  6, 12])

In [14]:
# x中大于3的位置为True
x > 3 

array([ True,  True,  True,  True, False,  True, False, False,  True,
        True])

In [15]:
# x中等于0的位置为True
x == 0

array([False, False, False, False, False, False,  True, False, False,
       False])

In [13]:
# 计算大于3的元素个数
np.sum(x>3)

7

In [7]:
X = x.reshape(5,-1)
X

array([[14,  8],
       [ 4,  4],
       [ 1,  6],
       [ 0,  2],
       [ 6, 12]])

In [8]:
# 二维数组与数值的比较，每个大于3的元素xij的位置均为True
X > 3 

array([[ True,  True],
       [ True,  True],
       [False,  True],
       [False, False],
       [ True,  True]])

In [9]:
np.sum(X>3)

7

In [10]:
# 计算x中非零元素个数
np.count_nonzero(x)

9

In [11]:
# python中bool数组默认True为1，False为0
# 故使用count_nonzero数出x>3结果中的True等价于计算x中大于3的元素个数
np.count_nonzero(x>3)

7

In [16]:
# any(x) bool数组中只要有一个True，返回结果即为True
# 判断x中是否含有零元素
np.any(x == 0)

True

In [17]:
# 判断x中是否有>15的元素
np.any(x>15)

False

In [18]:
# 判断x中所有元素是否均小于15
np.all(x<15)

True

In [20]:
# 计算x中>3并且<10的元素个数
np.sum((x>3)&(x<10))

5

In [23]:
# 注意上面的&是位运算符中的并，而不是条件运算符&&
# 相应的还有|或运算符以及~非运算符
# 计算x!=0的元素个数
np.sum(~(x==0))

9

numpy的fancy indexing 可以支持将bool数组传入array中，取出相应位置为True的元素

In [22]:
# 筛选出x中所有小于3的元素
x[x<3]

array([1, 0, 2])

In [33]:
# 筛选出X中最后一列小于8的所有行
# 首先取出最后一列
row = X[:, 1] 
row

array([ 8,  4,  6,  2, 12])

In [34]:
# 生成最后一列的bool数组
row_bool = row<8
row_bool

array([False,  True,  True,  True, False])

In [31]:
# 取出满足条件的所有行
X[row_bool, :]

array([[4, 4],
       [1, 6],
       [0, 2]])